namespace GameServerCore.Enums
{
    public enum BasicAttackTypes
    {
        BASICATTACK_NORMAL_SLOT1 = 0x40,
        BASICATTACK_NORMAL_SLOT2 = 0x41,
        BASICATTACK_NORMAL_SLOT3 = 0x42,
        BASICATTACK_NORMAL_SLOT4 = 0x43,
        BASICATTACK_NORMAL_SLOT5 = 0x44,
        BASICATTACK_NORMAL_SLOT6 = 0x45,
        BASICATTACK_NORMAL_SLOT7 = 0x46,
        BASICATTACK_NORMAL_SLOT8 = 0x47,
        BASICATTACK_NORMAL_SLOT9 = 0x48,
        BASICATTACK_CRITICAL_SLOT1 = 0x49,
        BASICATTACK_CRITICAL_SLOT2 = 0x4A,
        BASICATTACK_CRITICAL_SLOT3 = 0x4B,
        BASICATTACK_CRITICAL_SLOT4 = 0x4C,
        BASICATTACK_CRITICAL_SLOT5 = 0x4D,
        BASICATTACK_CRITICAL_SLOT6 = 0x4E,
        BASICATTACK_CRITICAL_SLOT7 = 0x4F,
        BASICATTACK_CRITICAL_SLOT8 = 0x50,
        BASICATTACK_CRITICAL_SLOT9 = 0x51,
        BASIC_ATTACK_TYPES_MAX_SLOT = 0x52,
        BASIC_ATTACK_TYPES_FIRST_SLOT = 0x40,
        BASICATTACK_NORMAL_LAST_SLOT = 0x48,
        BASICATTACK_CRITICAL_LAST_SLOT = 0x51
    }
}
