namespace GameServerCore.Enums
{
    public enum BuffType : byte
    {
        INTERNAL,
        AURA,
        COMBAT_ENCHANCER,
        COMBAT_DEHANCER,
        SPELL_SHIELD,
        STUN,
        INVISIBILITY,
        SILENCE,
        TAUNT,
        POLYMORPH,
        SLOW,
        SNARE,
        DAMAGE,
        HEAL,
        HASTE,
        SPELL_IMMUNITY,
        PHYSICAL_IMMUNITY,
        INVULNERABILITY,
        SLEEP,
        NEAR_SIGHT,
        FRENZY,
        FEAR,
        CHARM,
        POISON,
        SUPPRESSION,
        BLIND,
        COUNTER,
        SHRED,
        FLEE,
        KNOCKUP,
        KNOCKBACK,
        DISARM
    }
}