namespace GameServerCore.Enums
{
    public enum MoveOrder
    {
        MOVE_ORDER_ATTACKMOVE,
        MOVE_ORDER_ATTACKTERRAIN_ONCE,
        MOVE_ORDER_ATTACKTERRAIN_SUSTAINED,
        MOVE_ORDER_ATTACKTO,
        MOVE_ORDER_HOLD,
        MOVE_ORDER_MOVETO,
        MOVE_ORDER_PETHARDATTACK,
        MOVE_ORDER_PETHARDMOVE,
        MOVE_ORDER_PETHARDRETURN,
        MOVE_ORDER_PETHARDSTOP,
        MOVE_ORDER_STOP,
        MOVE_ORDER_TAUNT
    }
}